services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password 
    restart: unless-stopped
    volumes:
      - ./dbinit/dbinit.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: geincos
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - mynetwork

  nodeapp:
    container_name: nodeapp
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: '1234'
      DB_NAME: geincos
      SERVER_PORT: 3000
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
    depends_on:
      - mysqldb
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - mynetwork
    volumes:
      - ./nodeapp:/code

networks:
  mynetwork:
    driver: bridge